app/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

base/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django_resized import ResizedImageField
from django.conf import settings

# Create your models here.

class Proposta(models.Model):
	nome = models.CharField(max_length=30)
	email = models.EmailField()
	celular = models.CharField(max_length=11)


class Perfil(models.Model):
	ESTADOS = (
        ('ACRE', 'AC'),
        ('ALAGOAS', 'AL'),
        ('AMAPÁ', 'AP'),
        ('AMAZONAS', ''),
        ('BAHIA', 'BA'),
        ('CEÁRA', 'CE'),
        ('DISTRITO FEDERAL', 'DF'),
        ('ESPÍRITO SANTO', 'ES'),
        ('GOÍAS', 'GO'),
        ('MARANHÃO', 'MA'),
        ('MATO GROSSO ', 'MT'),
        ('MATO GROSSO DO SUL', 'MINAS'),
        ('MINAS GERAIS', 'MG'),
        ('PARA', 'PA'),
        ('PARANÁ', 'PR'),
        ('PARAÍBA', 'PB'),
        ('PERNAMBUCO', 'PE'),
        ('PIAUÍ', 'PI'),
        ('RIO DE JANEIRO', 'RJ'),
        ('RIO GRANDE DO NORTE', 'RN'),
        ('RIO GRANDE DO SUL', 'RS'),
        ('RONDÔNIA', 'RO'),
        ('RORAIMA','RR'),
        ('SANTA CATARINA', 'SC'),
        ('SÃO PAULO', 'SP'),
        ('SERGIPE', 'SE'),
        ('TOCANTINS', 'TO'),
    )
	nome = models.CharField(max_length=30)
	telefone = models.CharField(max_length=11)
	email = models.EmailField()
	Endereco = models.CharField(max_length=50)
	numero = models.CharField(max_length=5)
	complemento = models.CharField(max_length=25)
	cidade = models.CharField(max_length=30)
	estado =models.CharField(max_length=22,choices=ESTADOS)
	bairro = models.CharField(max_length=30)
	perfil_facebook = models.CharField(max_length=100)
	perfil_instagram = models.CharField(max_length=100)
	creci = models.CharField(max_length=6)
	estado_creci = models.CharField(max_length=22,choices=ESTADOS)

	
class Imagens(models.Model):
	imagem_perfil = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=False)
	imagem_capa = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=False)
	imagem_formulario = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=False)
    

class Anuncio (models.Model):
	NEGOCIACAO = (
		('VENDA','VENDA'),
		('ALUGA','ALUGA'),
		('COMPRA','COMPRA'),
		)

	STATUS = (
		('LANÇAMENTO','LANÇAMENTO'),
		('EM OBRAS','EM OBRAS'),
		('PRONTO PARA MORAR','PRONTO PARA MORAR'),
		)

	TIPO = (
		('APARTAMENTO','APARTAMENTO'),
		('CASA','CASA'),
		('TERRENO','TERRENO'),
		('COMERCIAL','COMERCIAL'),
		('GALPÃO','GALPÃO'),
		('CHACARÁ','CHACARÁ'),
		('SÍTIO','SÍTIO'),
		('FAZENDA','FAZENDA'),
		)
	

	negociacao = models.CharField(max_length=6, choices=NEGOCIACAO)
	status = models.CharField(max_length=18,choices=STATUS)
	tipo_imovel = models.CharField(max_length=12, choices=TIPO)
	titulo_anuncio = models.CharField(max_length=30)
	bairro = models.CharField(max_length=30)
	endereco =models.CharField(max_length=30)
	descricao = models.TextField(max_length=150)
	imagem1 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=False)
	imagem2 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=False)
	imagem3 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=False)
	imagem4 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=False)
	imagem5 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=False)
	imagem6 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=False,blank=True)
	imagem7 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=True,blank=True)
	imagem8 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=True,blank=True)
	imagem9 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG',null=True,blank=True)
	imagem10 = ResizedImageField(size=[660, 540], quality=100, upload_to='media/',force_format='PNG', null=True,blank=True)
	anunciado = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

app/forms.py
from django import forms
from .models import Proposta, Perfil, Anuncio

class PropostaForm(forms.ModelForm):
    class Meta:
        model = Proposta
        fields = '__all__'

class PerfilForm(forms.ModelForm):
	class Meta:
		model = Perfil
		fields = '__all__'

class AnuncioForm(forms.ModelForm):
	class Meta:
		model = Anuncio
		fields = (
			'negociacao',
			'status',
			'tipo_imovel',
			'titulo_anuncio',
			'bairro',
			'endereco',
			'descricao',
			'imagem1',
			'imagem2',
			'imagem3',
			'imagem4',
			'imagem5',
			'imagem6',
			'imagem7',
			'imagem8',
			'imagem9',
			'imagem10',
			
			)

app/views.py
from django.shortcuts import render
from .forms import PropostaForm
from .models import Imagens, Perfil

# Create your views here.

def index(request):
    if request.method == 'POST':
        formulario = PropostaForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return render(request, 'nix-imob/index.html')
    formulario = PropostaForm()
    img = Imagens.objects.all()
    dados = Perfil.objects.all()
    return render(request, 'nix-imob/index.html',{'formulario': formulario,'img':img,'dados': dados})

app/templates/nix-imob/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title></title>
</head>
   <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

     <!-- Fontawesome CSS -->
    <script src="https://kit.fontawesome.com/a69cec9c91.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="fontawesome/css/all.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet" />



    <style type="text/css">
       *{
    margin:0;
    padding:0;
  }

  .bg-pink{
    background: pink;
  }

  .fb-color{
    background: #3b5998;
  }

  #insta {
                background: radial-gradient(circle at 30% 107%, #fdf497 0%, #fdf497 0%, #fd5949 20%, #d6249f 60%, #285AEB 90%);
                -webkit-background-clip: text;
                /* Also define standard property for compatibility */
                background-clip: text;
                -webkit-text-fill-color: transparent;
  
               

                border-color: black;
  
            }
   .btn-pink{
    background-color:#ff00ff;
   }
   .btn-pink2{
    background-color:#ff409f;
   }
   
   .btn-pink3{
    background-color: #d02090;
   }

   .btn-pink4{
    background-color: #ff3e98;
   }
   
   .btn-pink5{
    background-color: #ffa0bd;
   }

   #id_nome, #id_email, #id_celular{
    width: 100%;
   }

    

    </style>

<body class="">
  <!-- Menu superior -->
  {% for imagens in img %}
  <header class="container-fluid"  style="border:1px solid black;">
    <div class="self-align-center ">
    <!-- Links Redes Sociais -->
          <span class=" aling-self-center ml-5"  >
          <!-- Link Instagram -->
          <i class="fab fa-instagram   display-5 ml-3  "  id="insta" aria-hidden="true"></i><span class=" m-1"></span>

          
          </span>

          <span  class="col-1 aling-self-center ml-5 "  >
            <!-- Link Facebook -->
          <i class="fab fa-facebook-square display-5  mx-1 " style="color: #3b5998;">/</i>
          </span>
      </div>
    
    <!--Capa -->
    <div class="row " >
      <!--Foto da Capa -->
      <div class="col-12 "><img class=" img-fluid  col-12 " style="border:1px solid red;" src="{{imagens.imagem_capa}}"></div>
      <nav class="navbar navbar-expand-lg navbar-dark   col-12
       mt-0  pb-1 pt-1  " >

      

      <div class=""  >
        <!--Menu Hamburguer -->
        <button class="navbar-toggler bg-warning " data-toggle="collapse" data-target="#navegacao2">
            <span class="navbar-toggler-icon "></span>
        </button>

        <!--Navegação -->
        <div class="collapse navbar-collapse m-0 " id="navegacao2">
            <ul class="navbar-nav mx-2">
                <li class="nav-item mx-2 mt-2">
                    <a href="" class="nav-link btn btn-warning   ml-5  text-dark w-100  " >Home</a>
                </li>

                <li class="nav-item mx-2 mt-2">
                    <a href="" class="nav-link btn btn-warning ml-5 text-dark w-100 ">Lançamentos</a>
                </li>
                <li class="nav-item mx-2 mt-2">
                    <a href="" class="nav-link btn btn-warning ml-5 text-dark w-100 ">Pronto para Morar</a>
                </li>
                <li class="nav-item mx-2 mt-2">
                    <a href="" class="nav-link btn btn-warning ml-5 text-dark w-100 ">Agende sua visita aos decorados</a>
                </li>
            </ul> 
        </div>
      </div>
    </nav>

    </div>
    
  </header>
  <!--Fim menu supeior -->

  <!--Area de Conteúdo -->
  <div class="container-fluid row d-none d-lg-block " style="border:1px solid black; height: 700px;">

  <div class="col-6" style="border:1px solid blue; float: right;">
    <img  class="img-fluid w-100" src="{{imagens.imagem_formulario}}">
  </div>

   <!--Formulario -->
  <div class="col-5 mb-5 mt-3 ml-5 px-5   " style="border:1px solid red;">
      <h4 class="text-center" >Formulario de Contato </h4>
      <form enctype="multipart/form-data" action = "" method = "POST" class="anuncio-form  aling-self-center mt-5  " style="border:1px solid red;height: 400px;  ">
        {% csrf_token %}
        <ul style=" list-style: none;" class=" col-12">
          {{ formulario.as_ul }}
        </ul>
        
      </form>
        
      
      
  <!--Fim formulario -->
  <div class=" mt-5 m-5"><input style="" type="submit" value="Enviar" class="ml-5 px-5">
      </div>
  </div>

  </div>

  <!--Conteúdo tamanho menor que MD -- >
    <!--Area de Conteúdo -->
  <div class="container-fluid row d-md-none " style="border:1px solid black;">

  <div class="" style="border:1px solid blue; float: right;">
    <img  class="img-fluid w-100" src="{{imagens.imagem_formulario}}">
  </div>

   <!--Formulario -->
  <div class="col-12 mb-5 mt-3  " style="border:1px solid red;">
      <h4 class="text-center" >Formulario de Contato2</h4>
      <form enctype="multipart/form-data" action = "" method = "POST" class="anuncio-form  aling-self-center  " style="border:1px solid red; ">
        {% csrf_token %}
        <ul style=" list-style: none;" class=" col-12">
          {{ formulario.as_ul }}
        </ul>
        
      </form>
        
      
      
  <!--Fim formulario -->
  <div class=" mt-5 ml-5 pl-3"><input style="" type="submit" value="Enviar" class="ml-5 px-5">
      </div>
  </div>

  </div>

  <!--Conteúdo tamanho menor que LG -- >
    <!--Area de Conteúdo -->
  <div class="container-fluid row d-lg-none d-none d-md-block d-lg-none " style="border:1px solid black;">

  <div class="col-12" style="border:1px solid blue; float: right;">
    <img  class="img-fluid w-100" src="{{imagens.imagem_formulario}}">
  </div>

   <!--Formulario -->
  <div class="col-12 mb-5 mt-3  " style="border:1px solid red;">
      <h4 class="text-center" >Formulario de Contato3</h4>
      <form enctype="multipart/form-data" action = "" method = "POST" class="anuncio-form  aling-self-center  " style="border:1px solid red; ">
        {% csrf_token %}
        <ul style=" list-style: none;" class=" col-12">
          {{ formulario.as_ul }}
        </ul>
        
      </form>
        
      
      
  <!--Fim formulario -->
  <div class=" my-3 btn col-12"><input style="" type="submit" value="Enviar" class="ml-5 px-5">
      </div>
  
  </div>

  </div>



  {% endfor%}

 

  

 
    {%for perfil in dados%}
    <footer class="">
      <div class="text-center">{{perfil.nome}}</div>
       <div class=" text-center">
    <!-- Links Redes Sociais -->
          <span class=" aling-self-center "  >
          <!-- Link Instagram -->
          <i class="fab fa-instagram    ml-3  "  id="insta" aria-hidden="true"></i><span class=" m-1">@heloboss</span>

          
          </span>

          <span  class="col-1 aling-self-center ml-5 "  >
            <!-- Link Facebook -->
          <i class="fab fa-facebook-square   mx-1 " style="color: #3b5998;">/HeloBoss</i>
          </span>
      </div>
      <!--Endereco-->
      <div class="text-center mb-5">{{perfil.Endereco}} nº{{perfil.numero}} {{perfil.bairro}} - {{perfil.cidade}}/{{perfil.estado}}</div>
      <hr class="m-0">


      <!-- Desenvolvido por -->
      <div class="text-center mt-0 " style="font-size: 0.5em;" >Desenvolvido por Antherus Desenvolvimento Web</div>
      <div style="font-size: 0.7em;" class="text-center ">www.antherus.com.br<span>
    <!-- Links Redes Sociais -->
          <span class=" aling-self-center ml-5"  >
          <!-- Link Instagram -->
          <i class="fab fa-instagram    ml-3  "  id="insta" aria-hidden="true"></i><span class=" m-1">@antherus</span>

          
          </span>

          <span  class="col-1 aling-self-center ml-5 "  >
            <!-- Link Facebook -->
          <i class="fab fa-facebook-square   mx-1 " style="color: #3b5998;">/antherus</i>
          </span>
      </span></div>
    <!-- Links Redes Sociais -->
          
    
    </footer>
    {%endfor%}



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>